services:
  streamproxy:
    build: .
    ports:
      - "4211:4211"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4211"]
      interval: 30s
      timeout: 10s
      retries: 3